### PR TITLE
Consolidate web modules

### PR DESCRIPTION
**Pull request by awoods**
Resolves: https://jira.duraspace.org/browse/FCREPO-1523

### CODE REVIEW

**Comment by acoburn** [comment]
This looks good to me. Tested with several different profile combinations. We do want to be careful about the possibility that different camel routes will want to use different `input.stream` values, but in that case, someone can make different builds of this web app (if that is the case, they most certainly would already know what they're doing).

I have another meeting right now, but can merge this afterwards

**Comment by acoburn** [comment]
@awoods before merging, can you update the base README file, updating references to audit-triplestore (should be fcrepo-audit-triplestore) and audit-triplestore-web (now part of the fcrepo-camel-webapp module)

**Comment by awoods** [comment]
Thanks, @acoburn. I will update the README. As for the `input.stream`, I assume we would want to use separate variables if different modules want different values.

**Comment by acoburn** [comment]
@awoods in the trivial case (i.e. most cases) the `input.stream` value will be the same. As part of the "Add indexing endpoints" ticket, we'll need to have an auxiliary input value for the two indexing modules (but not the audit stream). For now, we should leave it as it is.

**Comment by acoburn** [comment]
@awoods I'm going to merge this now and we can put the README updates in a separate PR

**Comment by acoburn** [comment]
Resolved via 3b012c7465f85000cfae34d2b74c89cb82c81c1d

**Pull request closed without merging**
