### PR TITLE
bare implementation of a triplestore router

### PR DESCRIPTION
**Pull request by acoburn**
This partially resolves https://jira.duraspace.org/browse/FCREPO-1421

A basic testing framework is in place along with the standard fcrepo maven configuration.

What is needed is an actual implementation of the AuditSparqlProcessor class and a corresponding expansion of the RouteTest class.

@escowles should be able to take things from here.

### CODE REVIEW

**Comment by awoods** [comment]
@acoburn, please add a top-level pom.xml that defines the <module>audit-triplestore</module> so that `mvn install` works (as expected) from the top of this project.

**Comment by acoburn** [comment]
@awoods working on that now -- would you like that part of this PR or as a separate one?

**Comment by awoods** [comment]
@acoburn, a separate commit in this PR that creates a top-level pom.xml would be great.

**Comment by acoburn** [comment]
@awoods OK, should be all set now. I also added a travis-ci file

**Pull request merged**
